# Generated by Django 5.0.1 on 2024-04-09 16:04

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0002_sessiontree'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=4096)),
                ('response', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.apikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.llm')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='apikey.memorytree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SessionTree',
        ),
    ]
