# Generated by Django 5.0.1 on 2024-01-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0003_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=1)),
                ('desc', models.TextField()),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
