# Generated by Django 5.0.1 on 2024-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0004_memorytree_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorytree',
            name='name',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
