# Generated by Django 5.0.1 on 2024-01-26 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0005_alter_key_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instance_type', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('hosted_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.llm')),
            ],
        ),
    ]
