# Generated by Django 5.0.1 on 2024-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0006_inferenceserver'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceserver',
            name='status',
            field=models.CharField(default='off', max_length=200),
        ),
    ]
