# Generated by Django 5.0.1 on 2024-04-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0007_instructiontree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructiontree',
            old_name='default',
            new_name='default_child',
        ),
        migrations.AddField(
            model_name='instructiontree',
            name='default_editor_template',
            field=models.TextField(default=''),
        ),
    ]
