# Generated by Django 5.0.1 on 2024-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0007_inferenceserver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceserver',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
