# Generated by Django 5.0.1 on 2024-02-01 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0008_inferenceserver_last_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceserver',
            name='last_message_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
