# Generated by Django 5.0.1 on 2024-02-02 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0009_alter_inferenceserver_last_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=4048)),
                ('response', models.CharField(max_length=4048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.key')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.llm')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
