# Generated by Django 5.0.1 on 2024-04-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0009_instructiontree_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtemplate',
            name='model',
        ),
        migrations.DeleteModel(
            name='AgentInstruct',
        ),
        migrations.DeleteModel(
            name='CustomTemplate',
        ),
    ]
