# Generated by Django 5.0.1 on 2024-02-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0011_llm_chat_template_promptresponse_type_customtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promptresponse',
            old_name='type',
            new_name='p_type',
        ),
    ]
