# Generated by Django 5.0.1 on 2024-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0012_rename_type_promptresponse_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceserver',
            name='availibility',
            field=models.CharField(default='Not Avaliable', max_length=200),
        ),
    ]
