# Generated by Django 5.0.1 on 2024-02-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0013_inferenceserver_availibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inferenceserver',
            old_name='availibility',
            new_name='availaibility',
        ),
    ]
