# Generated by Django 5.0.1 on 2024-02-24 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0016_alter_inferenceserver_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtemplate',
            name='bot_instruct',
            field=models.TextField(default=''),
        ),
    ]
