# Generated by Django 5.0.1 on 2024-03-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0017_customtemplate_bot_instruct'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='agent_availability',
            field=models.BooleanField(default=False),
        ),
    ]
