# Generated by Django 5.0.1 on 2024-03-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0019_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptresponse',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.apikey'),
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
