# Generated by Django 5.0.1 on 2024-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0021_vecterisedpromptresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VecterisedPromptResponse',
        ),
    ]
