# Generated by Django 5.0.1 on 2024-03-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0022_delete_vecterisedpromptresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptresponse',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
    ]
