# Generated by Django 5.0.1 on 2024-03-18 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0023_promptresponse_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceserver',
            name='alternative_url',
            field=models.URLField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inferenceserver',
            name='private_ip',
            field=models.GenericIPAddressField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inferenceserver',
            name='public_ip',
            field=models.GenericIPAddressField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='promptresponse',
            name='p_type',
            field=models.CharField(default='prompt', max_length=4096),
        ),
        migrations.AlterField(
            model_name='promptresponse',
            name='prompt',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='promptresponse',
            name='response',
            field=models.CharField(max_length=4096),
        ),
    ]
