# Generated by Django 5.0.1 on 2024-03-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0025_crypto_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='coin_aud_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='crypto',
            name='coin_usdt_rate',
            field=models.FloatField(default=0.0),
        ),
    ]
