# Generated by Django 5.0.1 on 2024-03-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0026_crypto_coin_aud_rate_crypto_coin_usdt_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crypto',
            old_name='coin_aud_rate',
            new_name='coin_usd_rate',
        ),
        migrations.RemoveField(
            model_name='crypto',
            name='coin_usdt_rate',
        ),
    ]
