# Generated by Django 5.0.1 on 2024-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0027_rename_coin_aud_rate_crypto_coin_usd_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='integrated_address',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apikey',
            name='payment_id',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
