# Generated by Django 5.0.1 on 2024-03-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0029_apikey_monero_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='current_block_num',
            new_name='block_height',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='status',
            new_name='locked',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='transaction_id',
            new_name='transaction_hash',
        ),
    ]
