# Generated by Django 5.0.1 on 2024-03-24 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0031_alter_paymenthistory_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(default='', max_length=400),
            preserve_default=False,
        ),
    ]
