# Generated by Django 5.0.1 on 2024-03-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0032_remove_paymenthistory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstruct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=10)),
                ('instruct', models.TextField(default='')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apikey.customtemplate')),
            ],
        ),
    ]
