# Generated by Django 5.0.1 on 2024-03-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apikey', '0033_agentinstruct'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstruct',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
