# Generated by Django 5.0.6 on 2024-07-10 13:25

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('server', '0001_initial'), ('server', '0002_sessiontree'), ('server', '0003_memorytree_delete_sessiontree'), ('server', '0004_memorytree_p_type'), ('server', '0005_memorytree_name'), ('server', '0006_memorytree_is_session_start_node_and_more'), ('server', '0007_instructiontree'), ('server', '0008_rename_default_instructiontree_default_child_and_more'), ('server', '0009_instructiontree_parent'), ('server', '0010_remove_customtemplate_model_delete_agentinstruct_and_more'), ('server', '0011_rename_price_llm_input_price_and_more'), ('server', '0012_apikey_user'), ('server', '0013_alter_apikey_user'), ('server', '0014_userinstructiontree'), ('server', '0015_userinstructiontree_displayed_name'), ('server', '0016_alter_userinstructiontree_code_and_more'), ('server', '0017_delete_article'), ('server', '0018_llm_context_length'), ('server', '0019_llm_is_self_host'), ('server', '0020_llm_base'), ('server', '0021_llm_max_history_length')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKEY',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('credit', models.FloatField(default=0.0)),
                ('monero_credit', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integrated_address', models.CharField(max_length=400)),
                ('payment_id', models.CharField(max_length=400)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=400)),
                ('balance', models.FloatField(default=0.0)),
                ('coin_usd_rate', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField(default=1)),
                ('desc', models.TextField()),
                ('chat_template', models.TextField(default='')),
                ('input_price', models.FloatField(default=0.0)),
                ('agent_availability', models.BooleanField(default=False)),
                ('output_price', models.FloatField(default=0.0)),
                ('context_length', models.IntegerField(default=4096)),
                ('is_self_host', models.BooleanField(default=True)),
                ('base', models.CharField(blank=True, max_length=200, null=True)),
                ('max_history_length', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designates the name of the tag.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InferenceServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('instance_type', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('alternative_url', models.URLField()),
                ('public_ip', models.GenericIPAddressField()),
                ('private_ip', models.GenericIPAddressField()),
                ('status', models.CharField(default='off', max_length=200)),
                ('last_message_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('availability', models.CharField(default='Not Available', max_length=200)),
                ('hosted_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.llm')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('integrated_address', models.CharField(max_length=400)),
                ('payment_id', models.CharField(max_length=400)),
                ('transaction_hash', models.CharField(max_length=400)),
                ('locked', models.BooleanField()),
                ('block_height', models.IntegerField(default=0)),
                ('crypto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.crypto')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.apikey')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='server.producttag'),
        ),
        migrations.CreateModel(
            name='PromptResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=4096)),
                ('response', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('p_type', models.CharField(default='prompt', max_length=4096)),
                ('input_cost', models.FloatField(default=0.0)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.apikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.llm')),
                ('number_input_tokens', models.IntegerField(default=0)),
                ('number_output_tokens', models.IntegerField(default=0)),
                ('output_cost', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='MemoryTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=4096)),
                ('response', models.CharField(max_length=4096)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.apikey')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.llm')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.memorytree')),
                ('p_type', models.CharField(default='prompt', max_length=4096)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_session_start_node', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructionTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(max_length=10)),
                ('instruct', models.TextField(default='')),
                ('default_child', models.BooleanField(default=False)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('default_editor_template', models.TextField(default='')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.instructiontree')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserInstructionTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.TextField(default='', max_length=10)),
                ('instruct', models.TextField(default='')),
                ('default_child', models.BooleanField(default=False)),
                ('default_editor_template', models.TextField(default='')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.userinstructiontree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('displayed_name', models.TextField(default='', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
