# Generated by Django 5.0.1 on 2024-04-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_memorytree_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorytree',
            name='is_session_start_node',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='memorytree',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
