# Generated by Django 5.1 on 2024-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0006_paymenthistory_billing_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="integrated_address",
            field=models.TextField(blank=True, max_length=106, null=True),
        ),
        migrations.AlterField(
            model_name="apikey",
            name="payment_id",
            field=models.TextField(blank=True, max_length=32, null=True),
        ),
    ]
