# Generated by Django 5.1 on 2024-08-24 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0007_alter_apikey_integrated_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Processed"), (2, "Pending")], default=1
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="unlock_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
