# Generated by Django 5.0.1 on 2024-04-10 13:54

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_rename_default_instructiontree_default_child_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructiontree',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='server.instructiontree'),
        ),
    ]
