# Generated by Django 5.1 on 2024-08-25 11:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0009_paymenthistory_failed_validate_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenthistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paymenthistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
