# Generated by Django 5.1 on 2024-08-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0010_paymenthistory_created_at_paymenthistory_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inferenceserver",
            name="availability",
        ),
        migrations.AddField(
            model_name="inferenceserver",
            name="availability_status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "AVAILABLE"), (2, "NOT_AVAILABLE"), (3, "TESTING")],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "PENDING"),
                    (2, "STOPPED"),
                    (3, "STOPPING"),
                    (4, "RUNNING"),
                    (5, "SHUTTING_DOWN"),
                    (6, "TERMINATED"),
                ],
                default=2,
            ),
        ),
    ]
