# Generated by Django 5.1 on 2024-08-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0011_remove_inferenceserver_availability_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inferenceserver",
            old_name="availability_status",
            new_name="availability",
        ),
    ]
