# Generated by Django 5.1 on 2024-08-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0012_rename_availability_status_inferenceserver_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inferenceserver",
            name="availability",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Available"), (2, "Not Available"), (3, "Testing")],
                default=2,
            ),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Pending"),
                    (2, "Stopped"),
                    (3, "Stopping"),
                    (4, "Running"),
                    (5, "Shutting Down"),
                    (6, "Terminated"),
                ],
                default=2,
            ),
        ),
    ]
