# Generated by Django 5.1 on 2024-08-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0013_alter_inferenceserver_availability_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inferenceserver",
            name="status",
        ),
    ]
