# Generated by Django 5.0.1 on 2024-05-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_userinstructiontree'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinstructiontree',
            name='displayed_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
