# Generated by Django 5.1 on 2024-08-28 01:59

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0015_inferenceserver_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingDatasetRecord",
            fields=[
                (
                    "datasetrecord_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="server.datasetrecord",
                    ),
                ),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=384, null=True
                    ),
                ),
            ],
            bases=("server.datasetrecord",),
        ),
    ]
