# Generated by Django 5.0.1 on 2024-05-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0015_userinstructiontree_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstructiontree',
            name='code',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinstructiontree',
            name='displayed_name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
