# Generated by Django 5.0.1 on 2024-05-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0016_alter_userinstructiontree_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
