# Generated by Django 5.1 on 2024-08-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0016_embeddingdatasetrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmbeddingDatasetRecord",
        ),
    ]
