# Generated by Django 5.0.1 on 2024-05-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0017_delete_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='context_length',
            field=models.IntegerField(default=4096),
        ),
    ]
