# Generated by Django 5.0.1 on 2024-06-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0018_llm_context_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='is_self_host',
            field=models.BooleanField(default=True),
        ),
    ]
