# Generated by Django 5.0.6 on 2024-07-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0019_llm_is_self_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='base',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
