# Generated by Django 5.0.6 on 2024-07-08 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0020_llm_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='max_history_length',
            field=models.IntegerField(default=0),
        ),
    ]
