# Generated by Django 5.0.6 on 2024-07-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0001_squashed_0021_llm_max_history_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crypto",
            name="coin",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="alternative_url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="availability",
            field=models.CharField(default="Not Available", max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="instance_type",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="status",
            field=models.CharField(default="off", max_length=255),
        ),
        migrations.AlterField(
            model_name="inferenceserver",
            name="url",
            field=models.URLField(max_length=255),
        ),
        migrations.AlterField(
            model_name="instructiontree",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="llm",
            name="base",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="llm",
            name="context_length",
            field=models.IntegerField(default=8192),
        ),
        migrations.AlterField(
            model_name="llm",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="memorytree",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="memorytree",
            name="p_type",
            field=models.CharField(default="prompt", max_length=8192),
        ),
        migrations.AlterField(
            model_name="memorytree",
            name="prompt",
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="memorytree",
            name="response",
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="p_type",
            field=models.CharField(default="prompt", max_length=8192),
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="prompt",
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="promptresponse",
            name="response",
            field=models.CharField(max_length=8192),
        ),
        migrations.AlterField(
            model_name="userinstructiontree",
            name="displayed_name",
            field=models.TextField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="userinstructiontree",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
