# Generated by Django 5.1 on 2024-08-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0021_dataset_is_embedding_dataset_delete_datasetrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="embeddingdatasetrecord",
            name="prompt",
        ),
        migrations.RemoveField(
            model_name="embeddingdatasetrecord",
            name="response",
        ),
        migrations.RemoveField(
            model_name="embeddingdatasetrecord",
            name="system_prompt",
        ),
        migrations.AddField(
            model_name="embeddingdatasetrecord",
            name="content",
            field=models.JSONField(default=dict),
        ),
    ]
