# Generated by Django 5.0.6 on 2024-07-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0024_finegrainapikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="finegrainapikey",
            name="first_three_char",
            field=models.TextField(default="???"),
        ),
        migrations.AddField(
            model_name="finegrainapikey",
            name="last_three_char",
            field=models.TextField(default="???"),
        ),
    ]
