# Generated by Django 5.1 on 2025-03-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0024_alter_dataset_default_content_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceserver',
            name='host_mode',
            field=models.IntegerField(choices=[(1, 'Local'), (2, 'AWS')], default=2),
        ),
        migrations.AlterField(
            model_name='llm',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
