# Generated by Django 5.0.6 on 2024-07-12 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_finegrainapikey_first_three_char_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPermissionWithoutContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('allow_chat', 'Global permission for chatroom'), ('allow_agent', 'Global permission for using agent'), ('allow_toolbox', 'Global permission for using toolbox'), ('allow_view_log', 'Global permission for viewing log'), ('allow_chat_api', 'Global permission for chat api'), ('allow_agent_api', 'Global permission for using agent api'), ('allow_toolbox_api', 'Global permission for using toolbox api'), ('allow_view_cost', 'Global permission for viewing cost'), ('allow_create_template', 'Global permission for creating template'), ('allow_data_synthesis', 'Global permission for using data synthesis')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_agent',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_chat',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_create_data',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_create_template',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_data_synthesis',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_view_cost',
        ),
        migrations.RemoveField(
            model_name='finegrainapikey',
            name='allow_view_log',
        ),
        migrations.AddField(
            model_name='finegrainapikey',
            name='master_key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='server.apikey'),
        ),
        migrations.AlterField(
            model_name='finegrainapikey',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
