# Generated by Django 5.1 on 2025-03-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0025_inferenceserver_host_mode_alter_llm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='llm',
            name='extra_body_availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inferenceserver',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
