# Generated by Django 5.0.6 on 2024-07-12 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0026_custompermissionwithoutcontenttype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apikey",
            options={
                "verbose_name": "Master API Key",
                "verbose_name_plural": "Master API Keys",
            },
        ),
        migrations.AlterModelOptions(
            name="finegrainapikey",
            options={
                "verbose_name": "FineGrain API Key",
                "verbose_name_plural": "FineGrain API Keys",
            },
        ),
    ]
