# Generated by Django 5.0.6 on 2024-07-13 11:06

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0027_alter_apikey_options_alter_finegrainapikey_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finegrainapikey",
            name="ttl",
            field=models.DurationField(default=datetime.timedelta(days=10), null=True),
        ),
    ]
