# Generated by Django 5.0.6 on 2024-07-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0029_alter_custompermissionwithoutcontenttype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstructiontree',
            name='displayed_name',
            field=models.TextField(default='', unique=True),
        ),
    ]
