# Generated by Django 5.0.6 on 2024-07-17 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0031_alter_userinstructiontree_displayed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinstructiontree',
            name='displayed_name',
            field=models.TextField(default=''),
        ),
    ]
