# Generated by Django 5.0.7 on 2024-07-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0037_alter_custompermissionwithoutcontenttype_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="apikey",
            name="ratelimit",
            field=models.TextField(default="5000/minute"),
        ),
    ]
