# Generated by Django 5.0.7 on 2024-07-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0038_apikey_ratelimit"),
    ]

    operations = [
        migrations.AddField(
            model_name="finegrainapikey",
            name="ratelimit",
            field=models.TextField(default="30/minute"),
        ),
    ]
