# Generated by Django 5.0.7 on 2024-08-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0039_finegrainapikey_ratelimit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.DeleteModel(
            name="CustomPermissionWithoutContentType",
        ),
        migrations.RemoveField(
            model_name="memorytree",
            name="p_type",
        ),
        migrations.RemoveField(
            model_name="promptresponse",
            name="p_type",
        ),
        migrations.AddField(
            model_name="memorytree",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "chatbot"),
                    (2, "chatbot_api"),
                    (3, "agent"),
                    (4, "agent_api"),
                    (5, "toolbox"),
                    (6, "toolbox_api"),
                    (7, "data_synthesis"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="promptresponse",
            name="type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "chatbot"),
                    (2, "chatbot_api"),
                    (3, "agent"),
                    (4, "agent_api"),
                    (5, "toolbox"),
                    (6, "toolbox_api"),
                    (7, "data_synthesis"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="instructiontree",
            name="instruct",
            field=models.TextField(default="", max_length=128000),
        ),
        migrations.AlterField(
            model_name="userinstructiontree",
            name="code",
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name="ProductTag",
        ),
    ]
