# Generated by Django 5.0.7 on 2024-08-05 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0040_remove_product_tags_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryTreeMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("prompt", models.TextField()),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "chatbot"),
                            (2, "chatbot_api"),
                            (3, "agent"),
                            (4, "agent_api"),
                            (5, "toolbox"),
                            (6, "toolbox_api"),
                            (7, "data_synthesis"),
                        ],
                        default=1,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_session_start_node", models.BooleanField(default=False)),
                ("path", models.TextField(unique=True)),
                (
                    "key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.apikey"
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.llm"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="MemoryTree",
        ),
    ]
