# Generated by Django 5.0.7 on 2024-08-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0041_memorytreemp_delete_memorytree"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorytreemp",
            name="path",
            field=models.TextField(max_length=9999999, unique=True),
        ),
    ]
