# Generated by Django 5.0.7 on 2024-08-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0042_alter_memorytreemp_path"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionTreeMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.TextField()),
                ("instruct", models.TextField(default="", max_length=128000)),
                ("default_child", models.BooleanField(default=False)),
                ("default_editor_template", models.TextField(default="")),
                ("is_session_start_node", models.BooleanField(default=False)),
                ("path", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="userinstructiontree",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="userinstructiontree",
            name="user",
        ),
        migrations.CreateModel(
            name="UserInstructionTreeMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("depth", models.PositiveIntegerField()),
                ("numchild", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.TextField()),
                ("instruct", models.TextField(default="", max_length=128000)),
                ("default_child", models.BooleanField(default=False)),
                ("default_editor_template", models.TextField(default="")),
                ("is_session_start_node", models.BooleanField(default=False)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("displayed_name", models.TextField(default="")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="InstructionTree",
        ),
        migrations.DeleteModel(
            name="UserInstructionTree",
        ),
    ]
