# Generated by Django 5.0.7 on 2024-08-05 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0043_instructiontreemp_remove_userinstructiontree_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructiontreemp",
            name="is_session_start_node",
        ),
        migrations.RemoveField(
            model_name="userinstructiontreemp",
            name="is_session_start_node",
        ),
    ]
