# Generated by Django 5.0.7 on 2024-08-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0044_remove_instructiontreemp_is_session_start_node_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memorytreemp",
            name="path",
            field=models.TextField(max_length=220000, unique=True),
        ),
    ]
